window.AlgoArt=window.AlgoArt||{};
(function(A){
'use strict';
var W=A.W||1400,H=A.H||1000;
var SERIES={field:'Orbital Studies',spiral:'Golden Trajectories',rects:'Recursive Divisions',burst:'Radiant Systems',network:'Connected Fields',organic:'Growth Systems',geometric:'Constructed Forms',scribble:'Automatic Marks'};
var PALETTE_NAMES={spectrum:'full-spectrum',golden:'golden-angle',marker:'classic marker',cmyk:'CMYK',primary:'primary-colour',neon:'neon',pastel:'pastel',earth:'earth-tone',warm:'warm',cold:'cool',mono:'monochrome'};
function n(v,fallback){v=Number(v);return Number.isFinite(v)?v:(fallback||0)}
function plural(v,one,many){return v===1?one:(many||one+'s')}
function words(s){return String(s||'').replace(/^.*?-/,'').replace(/-/g,' ').toLowerCase()}
function pct(v){return Math.round(n(v))+'%'}
function clean(text){return String(text||'').replace(/\s+/g,' ').trim()}
function pointOf(item){if(!item)return null;var x=item.x!=null?item.x:item.cx;var y=item.y!=null?item.y:item.cy;return Number.isFinite(Number(x))&&Number.isFinite(Number(y))?{x:Number(x),y:Number(y)}:null}
function centroid(items){var pts=(items||[]).map(pointOf).filter(Boolean);if(!pts.length)return{x:W/2,y:H/2};var sx=0,sy=0;pts.forEach(function(p){sx+=p.x;sy+=p.y});return{x:sx/pts.length,y:sy/pts.length}}
function region(p){p=p||{x:W/2,y:H/2};var hx=p.x<W*.38?'left':(p.x>W*.62?'right':'centre');var vy=p.y<H*.38?'upper':(p.y>H*.62?'lower':'middle');if(hx==='centre'&&vy==='middle')return 'centre';if(hx==='centre')return vy+' centre';if(vy==='middle')return 'centre '+hx;return vy+' '+hx}
function voidSummary(voids){if(!voids||!voids.length)return 'No large protected negative-space region is recorded for this composition.';var centres=voids.map(function(v){return{x:n(v.x)+n(v.w)/2,y:n(v.y)+n(v.h)/2}});if(voids.length===1)return 'A protected negative-space region sits around the '+region(centroid(centres))+'.';return voids.length+' protected negative-space regions are recorded, centred overall around the '+region(centroid(centres))+'.'}
function tierCounts(items){var out={hero:0,medium:0,small:0};(items||[]).forEach(function(item){if(item&&out[item.tier]!=null)out[item.tier]++});return out}
function maxDepth(items,key){var m=0;(items||[]).forEach(function(item){m=Math.max(m,n(item&&item[key],0))});return m}
function focalFrom(meta){meta=meta||{};var g=meta.guide||{},pool=[];if(meta.layout&&meta.layout.length)pool=meta.layout.filter(function(i){return i.tier==='hero'});if(!pool.length&&g.layout)pool=g.layout.filter(function(i){return i.tier==='hero'});if(!pool.length&&g.items)pool=g.items.filter(function(i){return i.tier==='hero'});if(!pool.length&&g.hubs)pool=g.hubs;if(!pool.length&&g.roots)pool=g.roots;if(!pool.length&&g.anchors)pool=g.anchors;if(!pool.length&&g.centres)pool=g.centres;if(!pool.length&&g.points)pool=g.points;return centroid(pool)}
function baseIntro(s,meta){return{series:SERIES[s.mode]||s.mode||'ALGO/ART',marker:String(s.pen||'marker').replace(/-/g,' '),palette:PALETTE_NAMES[s.palette]||String(s.palette||'deterministic'),strategy:words(meta&&meta.strategy),focal:region(focalFrom(meta))}}
function describeField(s,meta,b){var items=(meta&&meta.layout)||(meta&&meta.guide&&meta.guide.layout)||[];var t=tierCounts(items);var heroes=items.filter(function(i){return i.tier==='hero'});var focal=region(centroid(heroes));return{visual:'A field of '+items.length+' geometric marker forms is organised around '+(t.hero||'a small number of')+' dominant '+plural(t.hero,'form')+', with smaller marks building rhythm around the '+focal+'.',construction:'The '+(b.strategy||'field')+' strategy uses hero, medium and supporting tiers, φ-related scale relationships and scored placement rather than accepting the first random layout.'}}
function describeSpiral(s,meta,b){var g=meta&&meta.guide||{};var variant=String(g.variant||b.strategy||'trajectory').replace(/-/g,' ').toLowerCase();var pts=g.points||[],centres=g.centres||[];var movement=variant==='safe sweep'?'a canvas-crossing safety sweep':('a '+variant+' trajectory');return{visual:'The composition follows '+movement+' through the '+region(centroid(pts.length?pts:centres))+', with marker forms distributed along the path rather than on a regular grid.',construction:(variant==='safe sweep'?'V6 detected that the original trajectory did not place enough points on the visible canvas and substituted a deterministic SAFE-SWEEP. ':'')+'Golden-angle turns and φ-based growth or spacing organise '+pts.length+' sampled trajectory '+plural(pts.length,'point')+'.'}}
function describeRects(s,meta){var g=meta&&meta.guide||{},cells=g.cells||[],depth=maxDepth(cells,'depth');return{visual:'The artwork is divided into '+cells.length+' rectangular territories, with nested lines and shapes forming an architectural composition across the canvas.',construction:'Recursive cuts favour the 61.8% / 38.2% golden-section split. The recorded subdivision reaches depth '+depth+', and selected cells can be left open to preserve negative space.'}}
function describeBurst(s,meta){var g=meta&&meta.guide||{},hubs=g.hubs||[],rays=g.rays||[];var hubCount=hubs.length||1;return{visual:hubCount+' '+plural(hubCount,'radiating hub')+' organise '+rays.length+' outward '+plural(rays.length,'mark')+', concentrating visual energy around the '+region(centroid(hubs))+'.',construction:'The '+String(g.variant||'radiant').toLowerCase()+' family uses golden-angle stepping and φ-related radial distances so repeated marks spread without forming a simple evenly divided starburst.'}}
function describeNetwork(s,meta){var g=meta&&meta.guide||{},nodes=g.layout||meta.layout||[],edges=g.edges||[],t=tierCounts(nodes);var primary=edges.filter(function(e){return e&&e.primary}).length;return{visual:'A connected field of '+nodes.length+' nodes and '+edges.length+' links forms a graph-like marker composition, anchored by '+(t.hero||'several')+' dominant '+plural(t.hero,'node')+'.',construction:(primary?primary+' primary '+plural(primary,'connection')+' form the backbone. ':'')+'Node hierarchy inherits φ-based placement and scale, while link selection favours useful relationships and avoids unnecessary crossings.'}}
function describeOrganic(s,meta){var g=meta&&meta.guide||{},roots=g.roots||[],seg=g.segments||[],depth=seg.length?maxDepth(seg,'depth')+1:0;var rootCount=roots.length||1;return{visual:'A branching marker structure grows from '+rootCount+' '+plural(rootCount,'root')+' near the '+region(centroid(roots))+', splitting into '+seg.length+' visible branch '+plural(seg.length,'segment')+'.',construction:'Branch length falls by roughly 1/φ through successive generations, while golden-angle-derived turns create the organic spread. The recorded structure reaches '+depth+' '+plural(depth,'generation')+'.'}}
function describeConstructed(s,meta){var g=meta&&meta.guide||{},items=g.items||[],t=tierCounts(items);var heroes=items.filter(function(i){return i.tier==='hero'});return{visual:'Independent geometric forms are arranged as a constructed composition, with '+(t.hero||'a few')+' large anchor '+plural(t.hero,'form')+' and smaller supporting shapes around the '+region(centroid(heroes))+'.',construction:'The '+String(g.variant||'constructed').toLowerCase()+' family uses φ-biased focal positions, scale quantisation and golden-angle rotations while keeping each object compositionally independent.'}}
function describeScribble(s,meta){var g=meta&&meta.guide||{},anchors=g.anchors||[],count=anchors.length||1;return{visual:'Loose marker strokes gather into '+count+' main activity '+plural(count,'territory','territories')+', creating a gestural composition centred around the '+region(centroid(anchors))+'.',construction:'The '+String(g.variant||'automatic').toLowerCase()+' family constrains apparent spontaneity with φ-distributed anchors, φ-related stroke lengths and golden-angle direction changes.'}}
var MODE_FN={field:describeField,spiral:describeSpiral,rects:describeRects,burst:describeBurst,network:describeNetwork,organic:describeOrganic,geometric:describeConstructed,scribble:describeScribble};
A.describeArtwork=function(settings,meta){var s=settings||{},m=meta||{},b=baseIntro(s,m);var fn=MODE_FN[s.mode]||describeField;var d=fn(s,m,b);var short=clean('Abstract algorithmic marker artwork from ALGO/ART’s '+b.series+' series. '+d.visual);var long=clean(d.visual+' '+voidSummary(m.voids||[])+' The work uses a '+b.marker+' marker treatment, '+b.palette+' palette settings and '+pct(s.phiStrength)+' φ adherence.');var construction=clean(d.construction+' This description is generated from the artwork’s construction metadata, not inferred from the finished image.');return{altText:short,longDescription:long,constructionDescription:construction,focalRegion:b.focal,series:b.series,strategy:m.strategy||''}};
})(window.AlgoArt);
