import { SITE_URL } from './config.mjs';

function strategyName(stats, fallback) {
  const parts = String(stats || '').split(' / ');
  return parts.length > 1 ? parts[1].trim() : fallback.toUpperCase();
}

// Public gallery permalinks stay short enough for Threads' 500-character cap.
// The gallery card itself always retains the full exact-state remix URL.
export function artworkGalleryLink(item) {
  const id = String(item.id || '');
  const day = id.slice(0, 10);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(day)) return SITE_URL;
  return new URL(`gallery/${day}/#${encodeURIComponent(id)}`, SITE_URL).href;
}

export function makeCaptions(item) {
  const strategy = strategyName(item.stats, item.mode);
  const heading = `${item.series.toUpperCase()} / ${strategy}`;
  const format = item.settings.orientation === 'portrait' ? 'Portrait study · ' : '';
  const facts = `${format}Seed ${item.seed} · φ ${item.settings.phiStrength}% · ${item.settings.pen} marker`;

  return {
    instagram: [
      heading,
      facts,
      '',
      'The idea becomes a machine that makes the art.',
      '',
      'Generated by ALGO/ART.',
      `${SITE_URL}`,
      '',
      '#generativeart #algorithmicart #creativecoding #digitalart #generativedesign'
    ].join('\n'),
    threads: [
      heading,
      facts,
      '',
      'The idea becomes a machine that makes the art.',
      '',
      'View this artwork and open its exact remix state:',
      artworkGalleryLink(item)
    ].join('\n'),
    bluesky: [
      heading,
      facts,
      '',
      'The idea becomes a machine that makes the art.',
      '',
      'Explore & remix:',
      SITE_URL,
      '',
      '#generativeart #creativecoding'
    ].join('\n'),
    altText:
      `Abstract algorithmic marker artwork from ALGO/ART's ${item.series} system. ` +
      `Generated from seed ${item.seed} using golden-ratio composition rules and imperfect ${item.settings.pen} marker strokes.`
  };
}
