import { SITE_URL } from './config.mjs';

function strategyName(stats, fallback) {
  const parts = String(stats || '').split(' / ');
  return parts.length > 1 ? parts[1].trim() : fallback.toUpperCase();
}

// An editor link, NOT a gallery link: the app resolves the archived exact
// settings, renders the identical image, then expands the address bar to the
// full share URL. This keeps Threads/Bluesky within their caption limits.
export function editorArtworkLink(item) {
  const id=String(item.id||'');
  if (!/^\d{4}-\d{2}-\d{2}-(?:P\d{2}|\d{2})$/.test(id)) {
    throw new Error('Cannot link artwork without a valid daily archive ID: '+id);
  }
  const url=new URL(SITE_URL);
  url.searchParams.set('art',id);
  return url.href;
}

export function makeCaptions(item) {
  const strategy = strategyName(item.stats, item.mode);
  const heading = `${item.series.toUpperCase()} / ${strategy}`;
  const format = item.settings.orientation === 'portrait' ? 'Portrait study · ' : '';
  const facts = `${format}Seed ${item.seed} · φ ${item.settings.phiStrength}% · ${item.settings.pen} marker`;

  return {
    instagram: [
      heading,
      facts,
      '',
      'The idea becomes a machine that makes the art.',
      '',
      'Generated by ALGO/ART.',
      `${SITE_URL}`,
      '',
      '#generativeart #algorithmicart #creativecoding #digitalart #generativedesign'
    ].join('\n'),
    threads: [
      heading,
      facts,
      '',
      'The idea becomes a machine that makes the art.',
      '',
      'Open this exact image in the ALGO/ART editor:',
      editorArtworkLink(item)
    ].join('\n'),
    bluesky: [
      heading,
      facts,
      '',
      'The idea becomes a machine that makes the art.',
      '',
      'Open this exact image in the ALGO/ART editor:',
      editorArtworkLink(item),
      '',
      '#generativeart #creativecoding'
    ].join('\n'),
    altText:
      `Abstract algorithmic marker artwork from ALGO/ART's ${item.series} system. ` +
      `Generated from seed ${item.seed} using golden-ratio composition rules and imperfect ${item.settings.pen} marker strokes.`
  };
}
