import { SITE_URL } from './config.mjs';

function strategyName(stats, fallback) {
  const parts = String(stats || '').split(' / ');
  return parts.length > 1 ? parts[1].trim() : fallback.toUpperCase();
}

export function makeCaptions(item) {
  const strategy = strategyName(item.stats, item.mode);
  const heading = `${item.series.toUpperCase()} / ${strategy}`;
  const facts = `Seed ${item.seed} · φ ${item.settings.phiStrength}% · ${item.settings.pen} marker`;

  return {
    instagram: [
      heading,
      facts,
      '',
      'The idea becomes a machine that makes the art.',
      '',
      'Generated by ALGO/ART.',
      `${SITE_URL}`,
      '',
      '#generativeart #algorithmicart #creativecoding #digitalart #generativedesign'
    ].join('\n'),
    threads: [
      heading,
      facts,
      '',
      'The idea becomes a machine that makes the art.',
      '',
      'Open this exact artwork state:',
      item.shareUrl
    ].join('\n'),
    altText:
      `Abstract algorithmic marker artwork from ALGO/ART's ${item.series} system. ` +
      `Generated from seed ${item.seed} using golden-ratio composition rules and imperfect ${item.settings.pen} marker strokes.`
  };
}
